# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - powershell: |
      $PathToGlobalJson = Join-Path -Path $Env:BUILD_SOURCESDIRECTORY -ChildPath "global.json"
      $GlobalJson = Get-Content -Raw -Path  $PathToGlobalJson | ConvertFrom-Json
      $Version= $GlobalJson.sdk.version
      
      Write-Host ("##vso[task.setvariable variable=SdkVersion;]$Version")
    displayName: 'Parse global.json'

  - task: DotNetCoreInstaller@0
    displayName: 'Use .NET Core sdk $(SdkVersion)'
    inputs:
      version: '$(SdkVersion)'
  - script: dotnet build ./SimplCommerce.sln
    displayName: 'dotnet build'
  - script: ./run-tests.sh
    displayName: 'run tests'
  - task: PublishTestResults@2
    displayName: 'Publish Test Results **/*.trx'
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: VSTest
      testResultsFiles: '**/*.trx' 

- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - powershell: |
    $PathToGlobalJson = Join-Path -Path $Env:BUILD_SOURCESDIRECTORY -ChildPath "global.json"
    $GlobalJson = Get-Content -Raw -Path  $PathToGlobalJson | ConvertFrom-Json
    $Version= $GlobalJson.sdk.version
    
    Write-Host ("##vso[task.setvariable variable=SdkVersion;]$Version")
  displayName: 'Parse global.json'

  - task: DotNetCoreInstaller@0
    displayName: 'Use .NET Core sdk $(SdkVersion)'
    inputs:
      version: '$(SdkVersion)'
  - script: dotnet build ./SimplCommerce.sln
    displayName: 'dotnet build'
  - script: ./run-tests.sh
    displayName: 'run tests'
  - task: PublishTestResults@2
    displayName: 'Publish Test Results **/*.trx'
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: VSTest
      testResultsFiles: '**/*.trx' 

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - powershell: |
    $PathToGlobalJson = Join-Path -Path $Env:BUILD_SOURCESDIRECTORY -ChildPath "global.json"
    $GlobalJson = Get-Content -Raw -Path  $PathToGlobalJson | ConvertFrom-Json
    $Version= $GlobalJson.sdk.version
    
    Write-Host ("##vso[task.setvariable variable=SdkVersion;]$Version")
  displayName: 'Parse global.json'

  - task: DotNetCoreInstaller@0
    displayName: 'Use .NET Core sdk $(SdkVersion)'
    inputs:
      version: '$(SdkVersion)'
  - script: dotnet build ./SimplCommerce.sln
    displayName: 'dotnet build'
  - task: PowerShell@2
    inputs:
      filePath: .\run-tests.ps1
    displayName: 'run tests'
  - task: PublishTestResults@2
    displayName: 'Publish Test Results **/*.trx'
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: VSTest
      testResultsFiles: '**/*.trx' 

- job: LinuxRelease
  pool:
    vmImage: 'Ubuntu 16.04'
  variables:
    buildConfiguration: 'Release'
  steps:
  - powershell: |
      $PathToGlobalJson = Join-Path -Path $Env:BUILD_SOURCESDIRECTORY -ChildPath "global.json"
      $GlobalJson = Get-Content -Raw -Path  $PathToGlobalJson | ConvertFrom-Json
      $Version= $GlobalJson.sdk.version
      
      Write-Host ("##vso[task.setvariable variable=SdkVersion;]$Version")
    displayName: 'Parse global.json'

  - task: DotNetCoreInstaller@0
    displayName: 'Use .NET Core sdk $(SdkVersion)'
    inputs:
      version: '$(SdkVersion)'
  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'
  - script: ./run-tests.sh
    displayName: 'run tests'    
  - task: PublishTestResults@2
    displayName: 'Publish Test Results **/*.trx'
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: VSTest
      testResultsFiles: '**/*.trx' 
